stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data


  data_validation:
    cmd: python src/cnnClassifier/pipeline/stage_02_data_validation.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - MAX_IMBALANCE_RATIO
    outs:
      - artifacts/data_validation/status.txt
    metrics:
      - artifacts/data_validation/validation_report.json:
          cache: false


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_03_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/data_validation/status.txt
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5



  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_05_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_05_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
      - artifacts/evaluation/classification_report.json:
          cache: false
    plots:
      - artifacts/evaluation/confusion_matrix.png:
          cache: false
